In [21]:
## train, test 데이터 csv 파일 업로드 ##
import matplotlib.pyplot as plt
from keras.preprocessing.image import ImageDataGenerator
import pandas as pd
train_data = pd.read_csv('C:/Users/jkseo/Desktop/challenge/train_vision.csv')
test_data = pd.read_csv('C:/Users/jkseo/Desktop/challenge/test_vision.csv')

In [22]:
train_data

filename  label
0     face_3267.png      1
1      face_587.png      4
2     face_6585.png      4
3     face_3094.png      4
4     face_1170.png      4
5     face_7223.png      5
6     face_3872.png      1
7     face_4052.png      4
8     face_6433.png      1
9     face_5166.png      4
10    face_7396.png      4
11     face_590.png      4
12    face_2927.png      1
13    face_4695.png      4
14    face_1189.png      1
15     face_275.png      4
16    face_7365.png      1
17    face_1894.png      1
18    face_3997.png      3
19    face_1872.png      5
20    face_4391.png      4
21    face_1740.png      5
22    face_6807.png      4
23    face_7609.png      1
24    face_4594.png      4
25    face_1096.png      1
26    face_4224.png      4
27    face_2711.png      4
28    face_1888.png      1
29    face_1183.png      4
...             ...    ...
5820  face_2853.png      1
5821  face_3102.png      1
5822  face_6802.png      4
5823  face_6694.png      4
5824  face_6890.png      4
5825  face_5312.png      5
5826  face_4564.png      4
5827  face_6513.png      1
5828  face_3096.png      1
5829  face_5115.png      1
5830  face_3580.png      6
5831  face_5574.png      1
5832  face_6370.png      4
5833  face_3923.png      4
5834  face_2294.png      1
5835  face_6455.png      1
5836  face_6245.png      4
5837   face_461.png      5
5838   face_452.png      1
5839  face_1334.png      3
5840  face_2237.png      4
5841  face_3214.png      5
5842  face_3869.png      4
5843  face_2678.png      5
5844  face_7020.png      4
5845   face_692.png      4
5846  face_5357.png      4
5847  face_3280.png      1
5848  face_6319.png      4
5849  face_2912.png      1

[5850 rows x 2 columns]

In [23]:
tr = train_data.values
print(tr)

[['face_3267.png' 1]
 ['face_587.png' 4]
 ['face_6585.png' 4]
 ...
 ['face_3280.png' 1]
 ['face_6319.png' 4]
 ['face_2912.png' 1]]


In [24]:
## 파일 이름과 라벨을 각각 추출 ##
import keras

train_file_name = tr[0:, 0]
train_labels = tr[0:, 1] - 1
print(train_file_name)
print(train_labels)
print(train_file_name.shape)
print(train_labels.shape)
## 원핫 인코딩 ##
one_hot_labels = keras.utils.to_categorical(train_labels)
print(one_hot_labels)
print(one_hot_labels.shape)
y_train = one_hot_labels

['face_3267.png' 'face_587.png' 'face_6585.png' ... 'face_3280.png'
 'face_6319.png' 'face_2912.png']
[0 3 3 ... 0 3 0]
(5850,)
(5850,)
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
(5850, 6)


In [26]:
## train_vision 파일에 존재하는 이미지 경로 재설정 ##
import shutil

src = 'C:/Users/jkseo/Desktop/challenge/faces_images/'
dir = 'C:/Users/jkseo/Desktop/challenge/train_data/'

for i in range(len(train_file_name)):
    filename = train_file_name[i]
    shutil.move(src + filename, dir + filename)

In [27]:
## train image로 구성된 train dataset 구성 ##
import numpy as np
from keras.preprocessing import image
train_image = []

path = 'C:/Users/jkseo/Desktop/challenge/train_data'
for i in range(len(train_file_name)):
    img = image.load_img(path + '/' + train_file_name[i], target_size=(128, 128))
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
    
x_train = np.array(train_image)

In [31]:
## 이미지 학습을 위한 CNN 모델 구축 ##
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), input_shape=(128, 128, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (3, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(128, (3, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(256, (3, 3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Flatten()) 
model.add(layers.Dense(512))
model.add(layers.Activation('relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(6, activation="softmax"))

In [32]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 126, 126, 32)      896       
_________________________________________________________________
activation_15 (Activation)   (None, 126, 126, 32)      0         
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 63, 63, 32)        0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 61, 61, 64)        18496     
_________________________________________________________________
activation_16 (Activation)   (None, 61, 61, 64)        0         
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 30, 30, 64)        0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 28, 28, 128)       73856     
__________

In [33]:
model.compile(loss="categorical_crossentropy", optimizer='adam', metrics=['acc'])

In [34]:
model.fit(x_train, y_train, batch_size=32, epochs=20)

Epoch 1/20
5850/5850 [==============================] - 237s 41ms/step - loss: 1.3659 - acc: 0.4935
Epoch 2/20
5850/5850 [==============================] - 283s 48ms/step - loss: 0.8645 - acc: 0.6769
Epoch 3/20
5850/5850 [==============================] - 262s 45ms/step - loss: 0.5146 - acc: 0.8132
Epoch 4/20
5850/5850 [==============================] - 267s 46ms/step - loss: 0.3951 - acc: 0.8615
Epoch 5/20
5850/5850 [==============================] - 273s 47ms/step - loss: 0.3426 - acc: 0.8778
Epoch 6/20
5850/5850 [==============================] - 241s 41ms/step - loss: 0.2960 - acc: 0.8940
Epoch 7/20
5850/5850 [==============================] - 248s 42ms/step - loss: 0.2587 - acc: 0.9118
Epoch 8/20
5850/5850 [==============================] - 249s 43ms/step - loss: 0.2347 - acc: 0.9217
Epoch 9/20
5850/5850 [==============================] - 276s 47ms/step - loss: 0.2120 - acc: 0.9272
Epoch 10/20
5850/5850 [==============================] - 251s 43ms/step - loss: 0.1878 - acc: 0.9340

In [35]:
test = test_data.values
print(test)

test_file_name = test[0:, 0]
print(test_file_name)

[['face_2624.png']
 ['face_3385.png']
 ['face_5015.png']
 ...
 ['face_2020.png']
 ['face_4219.png']
 ['face_269.png']]
['face_2624.png' 'face_3385.png' 'face_5015.png' ... 'face_2020.png'
 'face_4219.png' 'face_269.png']


In [37]:
## 정확도 검증을 위한 test dataset 구성 ##
path = 'C:/Users/jkseo/Desktop/challenge/faces_images/faces_images'
test_image = []
for i in range(len(test_file_name)):
    img = image.load_img(path + '/' + test_file_name[i], target_size=(128, 128))
    img = image.img_to_array(img)
    img = img/255
    test_image.append(img)
test_img = np.array(test_image)
print(len(test_img))

2000


In [38]:
## 예측 결과 확인 ##
prediction = model.predict_classes(test_img)
print(prediction)

[0 0 0 ... 4 3 3]


In [39]:
prediction += 1
print(prediction)

[1 1 1 ... 5 4 4]


In [40]:
print(len(prediction))
print(prediction.shape)

2000
(2000,)


In [42]:
## csv 파일에 예측 라벨 쓰기 ## 
import csv

f = open('C:/Users/jkseo/Desktop/challenge/result.csv', 'w', newline='')
csv_writer = csv.writer(f)
for i in prediction:
    csv_writer.writerow([i])
    
f.close()